import { StyleSheet, Text, View } from 'react-native'
import React from 'react'
export const styles = StyleSheet.create({
    view: {
        width: "100%",
        height: "70%",
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    txtkenhphat: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#FC638F",
        width: "100%",
        height: "30%",
        top: "15%",
    },

    txttensukien1: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#4B4C8C",
        width: "100%",
        height: "30%",
        textAlign: "center",
    },
    txttensukien: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#4B4C8C",
        width: "100%",
        height: "30%",
    },
    txtevent: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#FC638F",
        width: "100%",
        height: "40%",
    },
    body2: {
        width: "35%",
        height: "100%",
        justifyContent: "center",
        marginLeft: "10%",
    },
    body1: {
        width: "65%",
        height: "100%",
        justifyContent: "center",
        marginLeft: "10%",
    },
    bodybodycon: {
        width: "49%",
        height: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
        flexDirection: "row",

    },
    bodybodycon1: {
        width: "49%",
        height: "100%",
        alignItems: "center",
    },
    bodyitemcon: {
        elevation: 2,
        width: "23%",
        height: "70%",
        backgroundColor: "#FFFFFF",
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    bodyitem11: {
        elevation: 1.5,
        width: "90%",
        height: "26%",
        backgroundColor: "#FFFFFF",
        borderRadius: 10,
        justifyContent: "space-evenly",
        alignItems: "center",
        flexDirection: "row",

    },
    bodyitem12: {
        width: "90%",
        height: "26%",
        borderRadius: 10,
        justifyContent: "space-around",
        flexDirection: "row",
        alignItems: "center",
    },
    txtten1: {
        textAlign: "center",
        fontWeight: "bold",
        fontSize: 20,
        color: "black",
        alignItems: 'center',
        width: "20%",
    },
    itemcothu: {
        width: "90%",
        height: "25%",
        backgroundColor: "#FFFFFF",
        borderRadius: 30,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
    },
    bodyitem2: {
        width: "40%",
        height: "100%",
        backgroundColor: "#E5E9F2",
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    bodyitem1: {
        width: "55%",
        height: "100%",
        backgroundColor: "#F9FAFF",
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "space-evenly",
    },
    body: {
        width: "100%",
        height: "80%",
        flexDirection: "row",
        justifyContent: "space-around",
    },
    txttimkiem: {
        width: "100%",
        height: "50%",
        backgroundColor: "white",
        borderRadius: 40,
        fontSize: 20,
        borderWidth: 1,
    },
    txtwelcom: {
        fontSize: 30,
        color: "black",
        alignItems: 'center',
        marginLeft: "5%",
    },
    txtadmin: {
        fontWeight: "bold",
        fontSize: 40,
        color: "black",
        alignItems: 'center',
        marginLeft: "5%",
    },
    title1: {
        width: "39%",
        height: "100%",
        justifyContent: "center",
    },
    title2: {
        width: "29%",
        height: "100%",
        justifyContent: "center",
        alignItems: "center",
    },
    title3: {
        width: "29%",
        height: "100%",
        justifyContent: "space-around",
        alignItems: "center",
        flexDirection: "row",
    },
    title: {
        width: "100%",
        height: "20%",
        justifyContent: "space-around",
        flexDirection: "row",
    },
    txtten: {
        textAlign: "center",
        fontWeight: "bold",
        fontSize: 25,
        color: "white",
        alignItems: 'center',
    },
    itemcon3: {
        width: "45%",
        height: "70%",
        backgroundColor: "#4748A2",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 10,
    },
    itemcon2: {
        width: "45%",
        height: "70%",
        backgroundColor: "#FC638F",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 10,
    },
    itemcon1: {
        width: "45%",
        height: "70%",
        backgroundColor: "#4748A2",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 10,
    },
    itemcon: {
        width: "45%",
        height: "70%",
        backgroundColor: "#FC638F",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 10,
    },
    item1: {
        backgroundColor: 'white',
        height: "40%",
        width: "70%",
        borderRadius: 10,
        justifyContent: 'space-around',
        alignItems: 'center',
        flexDirection: "row",
        margin: 10,

    },
    item: {
        marginTop: "10%",
        backgroundColor: '#FFFFFF',
        height: "60%",
        width: "90%",
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        margin: 10,
        backgroundColor: "white",
    }
})
const StyleTrangchu = () => {
  return (
    <View>
    </View>
  )
}

export default StyleTrangchu
