import { StyleSheet, Text, View } from 'react-native'
import React from 'react'
 export const styles = StyleSheet.create({
    viewne: {
        width: "25%",
        height: "100%",
        alignItems: "center",
        justifyContent: "center",
    },
    navconv2: {
        width: "50%",
        height: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
        flexDirection: "row",
    },
    navitemconv5: {
        width: "100%",
        height: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
        flexDirection: "row",
        borderRadius: 30,
        borderRightWidth: 1.5,
        borderColor: "white",
    },
    navitemconv2: {
        width: "100%",
        height: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
        flexDirection: "row",
        borderRadius: 30,
        borderLeftWidth: 1.5,
        borderColor: "white",
    },
    txtitemcong1: {
        color: "white",
        fontWeight: "bold",
    },
    txtitemcong: {
        color: "yellow",
        fontWeight: "bold",
    },
    navitem: {
        width: "100%",
        height: "100%",
        flexDirection: "row",
        justifyContent: "space-evenly",
        alignItems: "center",
    },
    txtInn: {
        color: "white",
        fontWeight: "bold",
    },
    navitemconv3: {
        width: "60%",
        height: "100%",
        alignItems: "center",
    },
    navitemcon1: {
        flexDirection: "row",
        width: "17%",
        height: "100%",
        justifyContent: "center",
    },
    navitemcon: {
        width: "25%",
        height: "100%",
        justifyContent: "space-between",
        alignItems: "center",
        borderRadius: 30,
        borderWidth: 1.5,
        borderColor: "white",
        flexDirection: "row",
    },
    nav: {
        width: "100%",
        height: "9%",
        marginTop: "0.5%",
        alignItems: "center",
        justifyContent: "center",
    },
    viewsetin: {
        width: "60%",
        height: "40%",
        justifyContent: "center",
        alignItems: "center",
    },
    bodyicon11: {
        borderColor: "#1bf526",
        borderRightWidth: 1,
        width: "100%",
        height: "70%",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
    },
    txtbangdiem: {
        color: "#1bf526",
        fontWeight: "bold",
    },
    bodyicon111: {
        width: "35%",
        height: "100%",
        alignItems: "center",
        justifyContent: "center",
    },
    bodyicon: {
        width: "20%",
        height: "100%",
        alignItems: "center",
        justifyContent: "center",
    },
    bodyicon1: {
        width: "40%",
        height: "100%",
        alignItems: "center",
        justifyContent: "center",
    },
    bodyvieicon1: {
        borderRadius: 20,
        width: "90%",
        height: "70%",
        borderWidth: 2,
        borderColor: "#1bf526",
        flexDirection: "row",
        justifyContent: "space-evenly",
    },
    txtbtn: {
        color: "white",
        fontWeight: "bold",
    },
    txtbtn1: {
        color: "red",
        fontWeight: "bold",
    },
    pr1: {
        width: "100%",
        height: "100%",
        justifyContent: "center",
        alignItems: "center",
    },
    itemitemcon: {
        backgroundColor: "#252a40",
        width: "32%",
        borderRadius: 10,
    },
    itemitem: {
        width: "100%",
        height: "50%",
        justifyContent: "space-evenly",
        flexDirection: "row",
        marginTop: "5%",
    },
    bodyviewicon: {
        width: "100%",
        height: "30%",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        marginTop: "5%",
    },
    view123: {
        width: "80%",
        height: "65%",
        borderRadius: 40,
        alignItems: "center",
        borderBottomWidth: 2,
        borderBottomColor: 'white',
    },
    viewicon: {
        justifyContent: "space-evenly",
        flexDirection: "row",
        width: "100%",
        height: "35%",
        alignItems: "center",
    },
    txtraceto: {
        color: "white",
        fontWeight: "bold"
    },
    txtraceto1: {
        color: "yellow",
        fontWeight: "bold"
    },
    itemcon2: {
        width: '20%',
        alignItems: 'center',
        borderColor: 'black',
        height: '100%',
        justifyContent: 'center',
        backgroundColor: 'white',
        flexDirection: 'row',
        justifyContent: 'space-around',
        borderColor: 'red',
        borderWidth: 1,
    },
    itemfooter: {
        flexDirection: 'row',
        width: '100%',
        height: '100%',
        justifyContent: 'space-evenly',
    },
    txt: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 20,
    },
    btn: {
        width: '90%',
        height: '40%',
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#252a40',
        marginTop: '3%',
    },
    chuyenluot: {
        alignItems: 'center',
        width: "90%",
        height: "40%",
        top: "5%",
        justifyContent: "center",
        borderRadius: 5,
        backgroundColor: "#252a40",
    },
    cooldow: {
        width: "50%",
        height: "100%",
        alignItems: "center",
        justifyContent: "center",
    },
    footer2: {
        alignItems: 'center',
        width: '30%',
        height: '70%',
        justifyContent: "center",
    },
    footer1: {
        borderRadius: 2,
        borderColor: 'red',
        borderWidth: 1,
        alignItems: 'center',
        width: '100%',
        height: '45%',
        flexDirection: 'row',
    },
    seconds: {
        alignItems: 'center',
        width: "100%",
        height: "100%",
        alignItems: 'center',
        justifyContent: "center",
    },
    text: {
        color: 'black',
        alignItems: 'center',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    itemcon3: {
        width: '80%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'black',
        height: '100%',
        justifyContent: 'center',
    },
    progress1: {
        height: '100%',
        width: '100%',
    },

    thoigianthem: {
        marginTop: "0.5%",
        justifyContent: 'center',
        flexDirection: 'row',
        width: '100%',
        height: '100%',
    },
    themluot: {
        backgroundColor: "#252a40",
        alignItems: 'center',
        width: '40%',
        height: '30%',
        justifyContent: 'center',
        flexDirection: 'row',
        borderRadius: 20,
        borderColor: "white",
        borderWidth: 1,

    },
    txttamdung: {
        fontSize: 18,
        color: "white",
        fontWeight: "bold"
    },
    giahan: {
        backgroundColor: "#252a40",
        alignItems: 'center',
        width: '59%',
        height: '30%',
        justifyContent: 'center',
        flexDirection: 'row',
        marginLeft: "1%",
        borderWidth: 1,
        borderRadius: 20,
        borderColor: "white",
    },
    checked: {
        borderWidth: 2,
        borderColor: "#fe0000",
        width: "100%",
        height: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
        borderRadius: 40,
        backgroundColor: "#252a40",
    },
    ischeked: {
        width: "100%",
        height: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
        borderRadius: 40,
        borderWidth: 2,
        borderColor: "white",
        backgroundColor: "#252a40",
    },

    txtheader: {
        color: "white",
        fontSize: 20,
        fontWeight: "bold",
    },
    navpr: {
        width: "23%",
        height: "50%",
        justifyContent: "center",
        borderRadius: 5,
        borderWidth: 1,
        borderColor: "white",
        flexDirection: "row",
        backgroundColor: "#252a40",
        alignItems: "center",
    },
    txtnavdiem: {
        color: "#01f406",
        fontWeight: "bold",
        textAlign: "center",
    },
    txtnavavg: {
        color: "#01f406",
        fontSize: 50,
        fontWeight: "bold",
        textAlign: "center",
    },
    icon: {
        color: "white",
        fontWeight: "bold",
        textAlign: "center",
        marginTop: "-16%",
    },
    txtbodydiem: {
        color: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
    },
    txtbodydiem1: {
        color: "#fe0000",
        fontWeight: "bold",
    },
    footeritem: {
        width: "100%",
        height: "100%",
    },
    footer: {
        marginTop: "0.5%",
        width: "100%",
        height: "20%",
        alignItems: "center",
    },
    txtname: {
        color: "#1bf526",
        fontSize: 30,
        fontWeight: "bold",
        width: "60%",
    },
    txtname1: {
        color: "#1bf526",
        fontWeight: "bold",
        width: "60%",
        textAlign: "right",
    },
    txtname11: {
        color: "#1bf526",
        fontSize: 30,
        fontWeight: "bold",
        width: "60%",
        textAlign: "right",
    },
    itemcon: {
        width: "60%",
        height: "80%",
        justifyContent: "center",
        alignItems: "center",
    },
    headeritemconv3: {
        width: "60%",
        height: "100%",
        alignItems: "center",
    },
    headeritemconv1: {
        flexDirection: "row",
        width: "30%",
        height: "100%",
        justifyContent: "center",
        marginTop: "1%",
    },
    headeritemcon: {
        flexDirection: "row",
        width: "100%",
        height: "100%",
        justifyContent: "space-evenly",
        marginTop: "-7%",
    },
    headeritemconv2: {
        width: "20%",
        height: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
        flexDirection: "row",
    },
    headeritem: {
        width: "100%",
        height: "15%",
        flexDirection: "row",
        justifyContent: "space-evenly",
        alignItems: "center",
    },
    header: {
        width: "100%",
        height: "10%",
    },
    bodyitemconv2: {
        backgroundColor: "#252a40",
        width: "35%",
        margin: "6%",
        height: "90%",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "white",
    },
    bodyitemconv1: {
        alignItems: "center",
        flexDirection: "row",
        width: "100%",
        height: "40%",
        justifyContent: "space-evenly",
    },
    bodyitemconv4: {
        alignItems: "center",
        width: "30%",
        height: "100%",
        justifyContent: "space-evenly",
    },
    bodyitemcon: {
        flexDirection: "row",
        width: "30%",
        height: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
    },
    bodyitem: {
        width: "90%",
        height: "100%",
        justifyContent: "space-evenly",
        flexDirection: "row",
    },
    body: {
        width: "100%",
        height: "50%",
        alignItems: "center",
    },
    img3: {
        borderRadius: 10,
        width: 100,
        height: 100
      },
    img2: {
        width: "33%",
        height: "150%",
        borderRadius: 70,
        // borderWidth: 1,
        // borderColor: "#1bf526",
        // backgroundColor: "#454b61"
    },
    img: {
        width: "33%",
        height: "150%",
    },
    img1: {
        width: "100%",
        height: "100%",
    },
    item: {
        width: "25%",
        height: "100%",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row"
    },
    item1: {
        width: "40%",
        height: "60%",
        justifyContent: "space-between",
        alignItems: "center",
        flexDirection: "row",
        borderRadius: 50,
        borderWidth: 1,
        borderColor: "#01f406",
    },
    item2: {
        width: "30%",
        height: "60%",
        justifyContent: "space-between",
        alignItems: "center",
        flexDirection: "row",
        backgroundColor: "#FF1724",
        borderRadius: 50,
    },
    titleitem: {
        justifyContent: 'space-around',
        flexDirection: 'row',
        width: "95%",
        height: "100%",
        alignItems: "center",
    },
    title: {
        width: "100%",
        height: "20%",
        alignItems: "center",
    }
});
const StyleLib = () => {
    return (
        <View>
        </View>
    )
}

export default StyleLib

